json.company_id employee.company.id
json.employee_id employee.id
json.name employee.name
json.address employee.address
json.age employee.age
json.job_position employee.job_position
json.phone employee.phone
json.hobbies employee.hobbies
json.date employee.date
json.created_at employee.created_at
